spring:
  application:
    name: spring-ai
  datasource:
    url: jdbc:postgresql://localhost:25432/spring_ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    google:
      genai:
        project-id: test-pj-484705
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always  # PostgreSQL에 스키마 자동 생성
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      # Spring AI가 만든 spring_ai_chat_memory 테이블을 JPA가 변경하지 않도록 validate 사용
      ddl-auto: validate
    show-sql: true